// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function add(x, y) {
  return x + y | 0;
}

function drawCircle(r) {
  return r + 1 | 0;
}

var score = 10;

var myInt = 9;

var x = 10;

var buddy = /* tuple */[
  10.5,
  20.5,
  20.5
];

var aR = /* Ok */Block.__(0, ["sadf"]);

var payloadResults = /* :: */[
  /* Ok */Block.__(0, [/* record */[/* data */"hi"]]),
  /* :: */[
    /* Ok */Block.__(0, [/* record */[/* data */"bye"]]),
    /* :: */[
      /* Error */Block.__(1, ["Something wrong happened!"]),
      /* [] */0
    ]
  ]
];

var greetings = /* Head */[
  "hello",
  /* Head */[
    "world",
    /* Head */[
      "how are you",
      /* Empty */0
    ]
  ]
];

exports.score = score;
exports.myInt = myInt;
exports.add = add;
exports.drawCircle = drawCircle;
exports.x = x;
exports.buddy = buddy;
exports.aR = aR;
exports.payloadResults = payloadResults;
exports.greetings = greetings;
/* No side effect */
