// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var firstTupple = /* tuple */[
  1,
  2
];

var secondTupple = /* tuple */[
  1,
  2
];

var isDeepEquals = Caml_obj.caml_equal(firstTupple, secondTupple);

var isShallowEquals = firstTupple === secondTupple;

console.log(isFinite(1234.0));

exports.firstTupple = firstTupple;
exports.secondTupple = secondTupple;
exports.isDeepEquals = isDeepEquals;
exports.isShallowEquals = isShallowEquals;
/* isDeepEquals Not a pure module */
