// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

console.log("Hello, BuckleScript and Reason!!");

var numbers = /* array */[
  1,
  2,
  3
];

var array1 = /* array */[
  1,
  2,
  3
];

var array2 = /* array */[
  1,
  2,
  3
];

var equalArr = Caml_obj.caml_equal(array1, array2);

var name = "Manik";

console.log(name);

console.log(equalArr);

var number = "Hello World";

var list = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

exports.numbers = numbers;
exports.number = number;
exports.list = list;
exports.array1 = array1;
exports.array2 = array2;
exports.equalArr = equalArr;
exports.name = name;
/*  Not a pure module */
