// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


console.log(20.0);

console.log(20.0);

function getCenterCoordinates() {
  return /* tuple */[
          10,
          20
        ];
}

console.log(/* tuple */[
      10,
      20
    ]);

var isInteger = true;

var isList = true;

console.log(isInteger);

var tupleWithInferedTypes = /* tuple */[
  23123.32,
  "Lalit",
  /* "M" */77
];

var ageAndName = /* tuple */[
  24,
  "Lil' Reason"
];

var my3dCoordinates = /* tuple */[
  20.0,
  30.5,
  100.0
];

var x = 20.0;

var y = 30.5;

var z = 100.0;

var a = 20.0;

exports.tupleWithInferedTypes = tupleWithInferedTypes;
exports.ageAndName = ageAndName;
exports.my3dCoordinates = my3dCoordinates;
exports.x = x;
exports.y = y;
exports.z = z;
exports.a = a;
exports.getCenterCoordinates = getCenterCoordinates;
exports.isInteger = isInteger;
exports.isList = isList;
/*  Not a pure module */
