// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


console.log(20.0);

function getCenterCoordinates() {
  return /* tuple */[
          10,
          20
        ];
}

console.log(/* tuple */[
      10,
      20
    ]);

var isInteger = true;

console.log(isInteger);

var ageAndName = /* tuple */[
  24,
  "Lil' Reason"
];

var my3dCoordinates = /* tuple */[
  20.0,
  30.5,
  100.0
];

var x = 20.0;

var y = 30.5;

var z = 100.0;

exports.ageAndName = ageAndName;
exports.my3dCoordinates = my3dCoordinates;
exports.x = x;
exports.y = y;
exports.z = z;
exports.getCenterCoordinates = getCenterCoordinates;
exports.isInteger = isInteger;
/*  Not a pure module */
