// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var meNextYear = /* record */[
  /* age */21,
  /* name */"Big Reason"
];

console.log(20);

console.log(21);

var baby = /* record */[
  /* fname */"Baby Reason",
  /* age */5
];

baby[/* age */1] = baby[/* age */1] + 1 | 0;

console.log(baby[/* age */1]);

var someHorsePower = /* record */[
  /* power */10,
  /* metric */true
];

function getAge(entity) {
  return entity[/* age */0];
}

var metric = true;

var kraken = /* record */[
  /* age */9999,
  /* hasTentacles */true
];

var me = /* record */[
  /* age */5,
  /* name */"Baby Reason"
];

exports.meNextYear = meNextYear;
exports.baby = baby;
exports.metric = metric;
exports.someHorsePower = someHorsePower;
exports.getAge = getAge;
exports.kraken = kraken;
exports.me = me;
/*  Not a pure module */
