// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var $$class = CamlinternalOO.create_table(["drive"]);

var ids = CamlinternalOO.new_methods_variables($$class, [
      "enableEnvy",
      "drive"
    ], ["hasEnvy"]);

var enableEnvy = ids[0];

var drive = ids[1];

var hasEnvy = ids[2];

CamlinternalOO.set_methods($$class, /* array */[
      drive,
      (function (self$1, speed) {
          Curry._2(self$1[0][enableEnvy], self$1, true);
          return speed;
        }),
      enableEnvy,
      (function (self$1, envy) {
          self$1[hasEnvy][0] = envy;
          return /* () */0;
        })
    ]);

function obj_init() {
  var self = CamlinternalOO.create_object_opt(0, $$class);
  self[hasEnvy] = [false];
  return self;
}

CamlinternalOO.init_class($$class);

var obj = obj_init(0);

exports.obj = obj;
/* class Not a pure module */
