// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

var myList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var anotherList = /* :: */[
  0,
  myList
];

var myArray = /* array */[
  "hello",
  "world",
  "how are you"
];

var firstItem = Caml_array.caml_array_get(myArray, 0);

Caml_array.caml_array_set(myArray, 0, "hey");

var secondItem = Caml_array.caml_array_get(myArray, 0);

Caml_array.caml_array_set(myArray, 1, "all");

var arrayLength = myArray.length;

console.log(secondItem);

console.log(arrayLength);

exports.myList = myList;
exports.anotherList = anotherList;
exports.myArray = myArray;
exports.firstItem = firstItem;
exports.secondItem = secondItem;
exports.arrayLength = arrayLength;
/*  Not a pure module */
