// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var myList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var anotherList = /* :: */[
  0,
  myList
];

exports.myList = myList;
exports.anotherList = anotherList;
/* No side effect */
