// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var MyLibrary = require("./myLibrary");

var message = "Great!";

console.log(message);

var myAccount = /* Facebook */Block.__(1, [
    "Josh",
    26
  ]);

var greeting;

greeting = typeof myAccount === "number" ? "Hi!" : (
    myAccount.tag ? "Hi Josh, you're " + (String(26) + "-year-old.") : "Hello Josh!"
  );

console.log(greeting);

function printName(name) {
  if (name) {
    console.log("The name is " + (String(name[0]) + ""));
    return /* () */0;
  } else {
    console.log("The name is undefined");
    return /* () */0;
  }
}

var myName = "Ashish";

printName(/* Some */[myName]);

console.log("The name is undefined");

function normalDraw(animal) {
  MyLibrary.draw(animal[0]);
  return /* () */0;
}

function betterDraw(animal) {
  MyLibrary.draw(animal[0]);
  return /* () */0;
}

normalDraw(/* MyFloat */Block.__(0, [10.0]));

betterDraw(/* MyFloat */Block.__(0, [10.0]));

var areYouCrushingIt = /* Yes */0;

var pet = /* Dog */0;

var friendAccount = /* Instagram */Block.__(0, ["Jenny"]);

exports.areYouCrushingIt = areYouCrushingIt;
exports.message = message;
exports.pet = pet;
exports.myAccount = myAccount;
exports.friendAccount = friendAccount;
exports.greeting = greeting;
exports.printName = printName;
exports.myName = myName;
exports.normalDraw = normalDraw;
exports.betterDraw = betterDraw;
/*  Not a pure module */
