// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var message = "Great!";

var areYouCrushingIt = /* Yes */0;

var pet = /* Dog */0;

exports.areYouCrushingIt = areYouCrushingIt;
exports.message = message;
exports.pet = pet;
/* No side effect */
