// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");

var class_tables = [
  0,
  0,
  0
];

function someFunction() {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], 0);
}

var class_tables$1 = [
  0,
  0,
  0
];

function otherFunction() {
  if (!class_tables$1[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables$1[0] = env_init;
  }
  return Curry._1(class_tables$1[0], 0);
}

var someInts = /* tuple */[
  10,
  20
];

var ten = 10;

var twenty = 20;

var somePerson = /* record */[
  /* name */"Guy",
  /* age */30
];

var name = "Guy";

var age = 30;

var n = "Guy";

var a = 30;

exports.someInts = someInts;
exports.ten = ten;
exports.twenty = twenty;
exports.somePerson = somePerson;
exports.name = name;
exports.age = age;
exports.n = n;
exports.a = a;
exports.someFunction = someFunction;
exports.otherFunction = otherFunction;
/* No side effect */
