// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function displayMenu() {
  return /* () */0;
}

var showMenu = true;

var isMorning = false;

exports.showMenu = showMenu;
exports.displayMenu = displayMenu;
exports.isMorning = isMorning;
/* No side effect */
