// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var data = /* GoodResult */Block.__(1, ["Product shipped!"]);

if (typeof data === "number") {
  throw [
        Caml_builtin_exceptions.match_failure,
        [
          "k_PatternMatching.re",
          10,
          2
        ]
      ];
} else if (!data.tag) {
  "Something's wrong. The error code is: " + String("Product shipped!");
}

var message;

if (typeof data === "number") {
  console.log("No such item found!");
  message = /* () */0;
} else {
  console.log("No such item found!");
  message = /* () */0;
}

var i = /* Left */Block.__(0, [1]);

var v = 1;

exports.data = data;
exports.message = message;
exports.i = i;
exports.v = v;
/*  Not a pure module */
