// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var foo = 5;

foo = 6;

var foo$1 = 5;

var five = foo$1;

foo$1 = 6;

var foo$2 = 15;

Pervasives.print_int(foo$2);

exports.five = five;
exports.foo = foo$2;
/*  Not a pure module */
