// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


var myPromise = new Promise((function (resolve, _) {
        return resolve(2);
      }));

myPromise.then((function (value) {
            console.log(value);
            return Promise.resolve(value + 2 | 0);
          })).then((function (value) {
          console.log(value);
          return Promise.resolve(value + 3 | 0);
        })).catch((function (err) {
        console.log("Failure!!", err);
        return Promise.resolve(-2);
      }));

exports.myPromise = myPromise;
/* myPromise Not a pure module */
