// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");

console.log("this is reason");

(( console.log('here is some javascript for you') ));

console.log("this is reason");

var x = ( 'here is a string from javascript' );

console.log(x + " back in reason land");

var y = ( 'something' );

console.log(/* tuple */[
      "a string" + y,
      10 + y | 0
    ]);

var x$1 = ( 'well-typed' );

console.log(x$1 + " back in reason land");

var jsCalculate = (
 function (numbers, scaleFactor) {
   var result = 0;
   numbers.forEach(number => {
     result += number;
   });
   return result * scaleFactor;
 }
);

function calculate(numbers, scaleFactor) {
  return Curry._2(jsCalculate, $$Array.of_list(numbers), scaleFactor);
}

console.log(Curry._2(jsCalculate, $$Array.of_list(/* :: */[
              1,
              /* :: */[
                2,
                /* :: */[
                  3,
                  /* [] */0
                ]
              ]
            ]), 10));

var tau = Math.PI * 2.0;

alert("hello");

exports.y = y;
exports.x = x$1;
exports.jsCalculate = jsCalculate;
exports.calculate = calculate;
exports.tau = tau;
/*  Not a pure module */
