// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var Q_TestJs = require("./Q_TestJs");

Q_TestJs.log("Ashish");

Q_TestJs.logWithTimeStamp("Ashish");

/*  Not a pure module */
